### ISSUE TITLE
Use account-wide token with Base class

### ISSUE THREAD

**Issue by unidesigner** [seatable/seatable-api-python#70]
Hi,

I have a shared base and wanted to access it via an account-wide token, but I get a permission denied error. Is there a way to do this using tokens instead of the Account object?

Thanks.

```
urlbase = f'https://seatableurl'
post = {'username': 'email', 'password': 'pass'}
r = requests.post(urlbase + '/api2/auth-token/', data=post)
base = Base(r.json()['token'], urlbase)
base.list_rows('mysheet')
```

**Comment by freeplant** [comment]
I suggest you check with the document or ask questions in the forum.
