### ISSUE TITLE
Updating link records

### ISSUE THREAD

**Issue by sswatson** [seatable/seatable-api-python#9]
When I try to update an entry in a field of type "Link to other records", I get a return value that indicates success, but then it seems the record in the table isn't actually updated. 

Furthermore, when I retrieve records of that type, I get actual values (the names of the linked records) rather than record ids. Airtable's API returns record ids for Link fields, and it seems like there's a strong case to be made for that approach, at least in that it provides a more complete reflection of the relational structure of the base.

Thanks for building this! I'm a big fan.

**Comment by freeplant** [comment]
The fix will be included in the next release.

**Comment by sswatson** [comment]
Following up: I saw that the new SeaTable version came out, and I tried this again. I found that link fields return a list of record IDs now (great!), but I still get the behavior where "success" is returned but the field doesn't actually update (as confirmed by looking at the web interface, and by pulling the data again using the API).

**Comment by freeplant** [comment]
Links are special, as they are not value of cells. You can find the API to update links here: https://docs.seatable.io/published/seatable-api/python/seatable-api.md#user-content-Add%20a%20Link

**Comment by sswatson** [comment]
Makes sense, thanks!
